### ISSUE TITLE
CSS not applied in preview in Chrome

### ISSUE THREAD

**Issue by elishacohen** [superhi/editor-issues#7]
When I am in the new editor in chrome, the preview shows the site I'm working on without CSS. This doesn't change whether I'm working on the html or the CSS code. I tried multiple different projects and they were all the same.

**Screenshots**
<img width="1440" alt="Screen Shot 2019-06-19 at 11 17 18 AM" src="https://user-images.githubusercontent.com/51991222/59753215-f036b900-9283-11e9-8273-9230b3dae657.png">
<img width="1440" alt="Screen Shot 2019-06-19 at 11 18 25 AM" src="https://user-images.githubusercontent.com/51991222/59753223-f462d680-9283-11e9-8dca-5daf7ae6ec2e.png">

**Device:**
 - OS: macOS 10.12.6
 - Browser: Chrome 74.0.3729.169 (Official Build) (64-bit)

**Additional context**
Example live site, which is not previewing correctly: week-2-homework-92.superhi.com
Editor url to same site: https://subeditor.superhi.com/projects/36879

**Comment by artcommacode** [comment]
Thanks for opening the issue @elishacohen! Could you please try opening the Editor in a new Incognito window — making sure that none of your Chrome Extensions are running — and let me know if that changes anything?

**Comment by elishacohen** [comment]
Just tried and turned off extensions. Unfortunately, same result:

<img width="1440" alt="Screen Shot 2019-06-19 at 11 25 20 AM" src="https://user-images.githubusercontent.com/51991222/59753653-e497c200-9284-11e9-921a-98cc2141121b.png">

**Comment by artcommacode** [comment]
Oh I see what's happening here now! The new Editor uses a slightly different rule for linking stylesheets than the current editor does: rather than looking for the presence of a `<head>` or `<body>` tag it instead looks for `<link rel="stylesheet">` tags and decides whether or not to add it's own then. So, because you have `<link href="https://fonts.googleapis.com/css?family=Space+Mono&display=swap" rel="stylesheet">` on line 1 of your HTML it's decided not to add any stylesheets itself. 

To note: `<link rel="stylesheet">` tags should go in the `<head>` of an HTML document rather than in the `<body>` and this is also how Google recommends you add their fonts. The _current_ Editor will actually do all of that for you anyway and this editor will too, once I've fixed https://github.com/superhi/editor-issues/issues/1.

**Comment by elishacohen** [comment]
Ah ya - I just checked and all the projects that I had opened had a google font link at the beginning of the html file. This project (week-2-project-9.superhi.com) which just starts with the content (no google fonts) previews fine:

<img width="1440" alt="Screen Shot 2019-06-19 at 11 37 35 AM" src="https://user-images.githubusercontent.com/51991222/59754626-bca95e00-9286-11e9-9072-03dc8eac3d0d.png">

**Comment by artcommacode** [comment]
Good to hear, thanks again! 👍
